import { setIcon } from '../shared/icons';
import { parseMonster } from '../../parsers/monster-parser';
import { parseSpell } from '../../parsers/spell-parser';
import { parseItem } from '../../parsers/item-parser';
import { renderMonsterBlock, initMonsterTabs } from '../../renderers/monster-renderer';
import { renderSpellBlock } from '../../renderers/spell-renderer';
import { renderItemBlock } from '../../renderers/item-renderer';

import { isDndCodeFence, parseDndCodeFence, type DndCodeFenceResult } from './dndCodeFence';

// Re-export pure functions and types for external consumers
export { isDndCodeFence, parseDndCodeFence, type DndCodeFenceResult } from './dndCodeFence';

export type CopyAndSaveCallback = (entityType: string, yamlSource: string, name: string) => Promise<string | undefined> | void;

/**
 * Inserts trusted HTML from our own renderers into a DOM element.
 * The renderers (renderMonsterBlock, renderSpellBlock, renderItemBlock)
 * produce sanitized HTML from parsed YAML data -- no raw user input.
 *
 * This is NOT user-supplied content: the render pipeline is
 * YAML parse -> typed interface -> HTML template with escapeHtml().
 */
function setTrustedRendererHtml(el: HTMLElement, html: string): void {
  // eslint-disable-next-line no-unsanitized/property
  el.innerHTML = html;
}

/**
 * Renders a D&D entity stat block into the given container element.
 * Uses archivist-logseq's existing parsers/renderers which return HTML strings.
 */
export function renderDndEntityBlock(
  doc: Document,
  containerEl: HTMLElement,
  result: DndCodeFenceResult,
  onCopyAndSave?: CopyAndSaveCallback,
): void {
  const wrapper = doc.createElement('div');
  wrapper.className = 'claudian-dnd-entity-block';
  containerEl.appendChild(wrapper);

  // Source badge
  const badge = doc.createElement('div');
  badge.className = 'claudian-dnd-source-badge';
  badge.textContent = result.entityType;
  wrapper.appendChild(badge);

  // Render the stat block using the appropriate parser and renderer
  let statBlockHtml: string | null = null;

  switch (result.entityType) {
    case 'monster': {
      const parsed = parseMonster(result.yamlSource);
      if (parsed.success) {
        statBlockHtml = renderMonsterBlock(parsed.data);
      }
      break;
    }
    case 'spell': {
      const parsed = parseSpell(result.yamlSource);
      if (parsed.success) {
        statBlockHtml = renderSpellBlock(parsed.data);
      }
      break;
    }
    case 'item': {
      const parsed = parseItem(result.yamlSource);
      if (parsed.success) {
        statBlockHtml = renderItemBlock(parsed.data);
      }
      break;
    }
  }

  if (statBlockHtml) {
    const temp = doc.createElement('div');
    temp.className = 'archivist-stat-block-wrapper';
    setTrustedRendererHtml(temp, statBlockHtml);
    wrapper.appendChild(temp);

    // Wire tab click handlers (monster blocks have TRAITS/ACTIONS/REACTIONS tabs)
    if (result.entityType === 'monster') {
      initMonsterTabs(temp);
    }
  } else {
    // Fallback: show raw YAML in a pre block
    const fallback = doc.createElement('pre');
    fallback.className = 'claudian-dnd-fallback';
    wrapper.appendChild(fallback);

    const code = doc.createElement('code');
    code.textContent = result.yamlSource;
    fallback.appendChild(code);
  }

  // Action buttons
  if (onCopyAndSave) {
    const actionsRow = doc.createElement('div');
    actionsRow.className = 'claudian-dnd-actions';
    wrapper.appendChild(actionsRow);

    renderCopyAndSaveButton(doc, actionsRow, result, onCopyAndSave);
  }
}

/** Copy & Save button for entities. */
function renderCopyAndSaveButton(
  doc: Document,
  actionsRow: HTMLElement,
  result: DndCodeFenceResult,
  onCopyAndSave: CopyAndSaveCallback,
): void {
  const btn = doc.createElement('button');
  btn.className = 'archivist-dnd-action-btn';
  actionsRow.appendChild(btn);

  const iconSpan = doc.createElement('span');
  setIcon(iconSpan, 'save');
  btn.appendChild(iconSpan);

  const labelSpan = doc.createElement('span');
  labelSpan.textContent = 'Copy & Save';
  btn.appendChild(labelSpan);

  btn.addEventListener('click', async () => {
    const slugResult = await onCopyAndSave(result.entityType, result.yamlSource, result.name);
    const slug = typeof slugResult === 'string' ? slugResult : undefined;

    // Copy widget reference or code fence fallback
    const refText = slug
      ? `{{${result.entityType}:${slug}}}`
      : '```' + result.entityType + '\n' + result.yamlSource + '\n```';
    try {
      await navigator.clipboard.writeText(refText);
    } catch { /* clipboard may fail */ }

    // Update button to show success
    if (slug) {
      labelSpan.textContent = 'Saved!';
      setTimeout(() => { labelSpan.textContent = 'Copy & Save'; }, 2000);
    }
  });
}

/**
 * Scans an element for D&D code fence divs (generated by markdown.ts)
 * and replaces them with rendered stat blocks.
 */
export function replaceDndCodeFences(
  doc: Document,
  el: HTMLElement,
  onCopyAndSave?: CopyAndSaveCallback,
): void {
  // Look for the divs created by our custom markdown-it fence rule
  const fenceDivs = el.querySelectorAll('.archivist-dnd-fence');
  for (const fenceDiv of Array.from(fenceDivs)) {
    const language = (fenceDiv as HTMLElement).dataset.lang;
    if (!language || !isDndCodeFence(language)) continue;

    const codeEl = fenceDiv.querySelector('code');
    const yamlSource = codeEl?.textContent || '';
    const result = parseDndCodeFence(language, yamlSource);
    if (!result) continue;

    const parent = fenceDiv.parentElement;
    if (!parent) continue;

    const container = doc.createElement('div');
    parent.insertBefore(container, fenceDiv);
    fenceDiv.remove();

    renderDndEntityBlock(doc, container, result, onCopyAndSave);
  }

  // Also handle standard <pre><code class="language-monster"> blocks
  const codeBlocks = el.querySelectorAll('pre > code');
  for (const code of Array.from(codeBlocks)) {
    const classMatch = code.className.match(/language-(\w+)/);
    if (!classMatch) continue;

    const language = classMatch[1];
    if (!isDndCodeFence(language)) continue;

    const yamlSource = code.textContent || '';
    const result = parseDndCodeFence(language, yamlSource);
    if (!result) continue;

    const pre = code.parentElement;
    if (!pre) continue;

    const parent = pre.parentElement;
    if (!parent) continue;

    const container = doc.createElement('div');
    parent.insertBefore(container, pre);
    pre.remove();

    renderDndEntityBlock(doc, container, result, onCopyAndSave);
  }
}
